liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets: # Contient la liste des filtres
        carre: # Nom du filtre
            quality: 75 # Qualité de l'image
            filters: # Liste des filtres à appliquer
                thumbnail: # Filtre "Thumbnail"
                    size: [200, 200] # Taille de l'image de sortie
                    mode: outbound # Découpage de l'image
        reduc:
            quality: 85
            filters:
                scale:
                    dim: [ 250, 250 ]
        article:
            quality: 80
            filters:
                upscale:
                    min: [800, 400]
                thumbnail:
                    size: [800, 400]
                    mode: outbound
                watermark:
                    # chemin vers le fichier
                    image: ../public/assets/img/watermark.png
                    # Taille relative de l'image
                    size: 0.1
                    # set the position of the watermark
                    position: bottomright
