twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: 
        ['bootstrap_4_layout.html.twig',
        '@FOSCKEditor/Form/ckeditor_widget.html.twig'] # accepte plusieurs thèmes
fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote', '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'Image', 'Table', '-', 'Styles', 'Format','Font','FontSize', '-', 'TextColor', 'BGColor', 'Source'] }
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
vich_uploader:
    db_driver: orm 
    mappings:
        featured_images:
            uri_prefix: '%app.path.featured_images%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            upload_destination: '%kernel.project_dir%/public%app.path.featured_images%'

# stof_doctrine_extensions:
#     default_locale: fr_FR
#     orm:
#         default:
#             sluggable: true
#             timestampable: true
    # mappings:
    #     property_image:
    #         uri_prefix: /images/properties
    #         upload_destination: '%kernel.project_dir%/public/images/properties'



   
